### ISSUE TITLE
Latest version does not appear to be pushed to Bower

### ISSUE THREAD

**Issue by michaelryancaputo** [jfmdev/ngComboDatePicker#10]
Bower package repository does not contain version 1.2.2.

My expectation would be that if I specify `"ngComboDatePicker": "^1.2.2"` in my bower.json file, that the version 1.2.2 would load.

**Comment by jfmdev** [comment]
Bower currently detects that the last version if **1.2.2**

> You can verify it by executing `bower info ngComboDatePicker` or `bower info ngComboDatePicker#1.2.2`

It probably was a cache issue (since release 1.2.2 was published the same day in which this issue was opened).

**Comment by michaelryancaputo** [comment]
I'm still only getting 1.2.1 locally here when I delete the bower_components folder, open the ngComboDatePicker folder, and look at the bower.json file. It displays as 1.2.1. I can confirm the steps you provided above show 1.2.2.

I have done a `bower cache clean` and `bower install --force` and cleared my bower_components folder a few times to try and get this working.

**Comment by jfmdev** [comment]
The file `bower.json` says the version is _1.2.1_, but if you open the file `ngComboDatePicker.js` (or `ngComboDatePicker.min.js`) you will see that the version is **1.2.2**.

> Release 1.2.2 was made before updating the files `bower.json` and `package.json`, so these files display an incorrect version number, which is not a big issue, since you are still getting the correct version of `ngComboDatePicker.js` and `ngComboDatePicker.min.js`.

**Comment by michaelryancaputo** [comment]
Ok, shouldn't the version numbers match? It also does not match in the package.json

**Comment by michaelryancaputo** [comment]
My production environment doesn't seem to be registering the change either unfortunately.
