### ISSUE TITLE
Can these ng-model validation against min and max be disabled?

### ISSUE THREAD

**Issue by surendrakashyap** [jfmdev/ngComboDatePicker#13]
This validation cause actual model value to change to min or max. That means we are initialing model for user which I want  to avoid.

 // Verify if selected date is in the valid range.
            if($scope.ngModel < $scope.minDate) $scope.ngModel = $scope.minDate;
            if($scope.ngModel > $scope.maxDate) $scope.ngModel = $scope.maxDate;

**Comment by jfmdev** [comment]
Hi,

The code:

``` js
if($scope.ngModel < $scope.minDate) $scope.ngModel = $scope.minDate;
if($scope.ngModel > $scope.maxDate) $scope.ngModel = $scope.maxDate
```

Is only executed once, to verify that the attribute `ng-model` has a valid value. However, if you initializes the model with `null`, then this code is not executed and the combo boxes are going to be blank.

For example:

``` html
<script type="text/javascript">
    app.controller('myController', function ($scope) {
        $scope.myDateModel = null;
    });
</script>
<div ng-controller="myController">
    <p>Choose a date: <ng-combo-date-picker ng-model="myDateModel"></ng-combo-date-picker></p>
    <p>Current selection is: <strong>{{ myDateModel }}</strong>
</div>
```
