### ISSUE TITLE
Regression: wrong date selection when minimal date is enabled

### ISSUE THREAD

**Issue by MBach** [jfmdev/ngComboDatePicker#16]
Since release 1.3.0,

If I set a minimal date to Toay for example, I can only select Month: December, and Days: 08-09-...-31.

However, when I switch Year to 2017, the Month is still December, and not Jan. to Dec.

This didn't happen on release 1.2.5

**Comment by jfmdev** [comment]
Hi **MBach**, thank you for informing about this error, I have made a new release (1.3.1) that fixs the bug. Regards

**Comment by MBach** [comment]
Nice job! It's working fine
