### ISSUE TITLE
Select by month is not accesible

### ISSUE THREAD

**Issue by asanchez75** [jfmdev/ngComboDatePicker#20]
Hi

If months labels in english are replaced by months in spanish, the selector by month is not accessible from the keyboard in Android.  I used Angularjs and Ionic.

Regards,

**Comment by jfmdev** [comment]
Hi Adam,

I have tested the library in several mobile devices without finding any issues, can you: 
 * Share the code which is giving you troubles?
 * Verify if you are also getting this error when opening the [docs](http://jfmdev.github.io/ngComboDatePicker/) page in your mobile device?
 * Indicate which Android device are you using?

Best regards

**Comment by jfmdev** [comment]
Closed due to inactivity
