### ISSUE TITLE
Year values are not displaying 

### ISSUE THREAD

**Issue by pavan2540** [jfmdev/ngComboDatePicker#22]
when we are  dynamically  creating forms  , in three field's datepicker  date &month values showing properly ,only  year value is not showing.

**Comment by pavan2540** [comment]
got a solution , so im closing the issue

**Comment by ajayreddy56** [comment]
i am facing this issue.how you resolved?can you tell me

**Comment by jfmdev** [comment]
@ajayreddy56 If you share the code in which you are getting this error, I could help you
