### ISSUE TITLE
Datefields control does not honor "required"

### ISSUE THREAD

**Issue by pavan2540** [jfmdev/ngComboDatePicker#23]
The 3-field date picker was updated to add the custom class necessary for displaying the "required" marker does not actually honor the setting for "required". If the schema is tagger as "required", the data can still be submitted even if no data is entered (all 3 fields blank).

**Comment by jfmdev** [comment]
Hello,

I'm not sure how do you configured your `<ng-combo-date-picker>` instance, nor how do your _submit method_ verifies that the form is valid (the standard way if to verify that `$scope.your_form_name.$valid` is `true`).  
However if you take a look at the following example: https://plnkr.co/edit/x0JQ4xJKOAkOe1vmBd2C?p=preview

You will see that when using the following code:
```html
<form name="myForm" novalidate>
    <ng-combo-date-picker 
        ng-model="myDate" 
        name="my_date" 
        ng-required="true">
    </ng-combo-date-picker>
</form>
```

The variables `$scope.myForm.$valid` and `$scope.myForm.my_date.$error.required` are updated accordingly to the date picker being empty or not.

**Comment by pavan2540** [comment]
```js
$scope.schema = {
    "type" : "object",
    "properties": {
        "DOB":{
            "type":"string",
            "title":"Date of Birth",
            "format":"datefields",
            "timezone": "0",
            "minDate": "1940-01-01",
            "maxDate": "2017-01-01",
            "order": "dmy",
            "yearOrder": "desc",
            "required" :"true",
            "description": "Provide your date in Day / Month / Year format"
        }
    },
    "required": ["DOB"]
};

$scope.form = [ 
    "DOB",
    {"type": "submit", "title": "OK"}
]
``` 

Example above code is our schema which is coming from dynamically ,  

` <form sf-schema="schema" sf-form="form" sf-model="model">`

The above code is the code for using in view side ,  in the schema  we are passing "required":"true"  , but still we can able to submit empty datefields ,

**Comment by jfmdev** [comment]
I'm not very familiar with _Angular Schema Form_, but it seems that their API requires to explicitly create an add-on in order to use custom directives within their forms.  
Unfortunately, I have no plans on adding support for this library.
