### ISSUE TITLE
NgModelController states (e.g. $touched) are not propagated 

### ISSUE THREAD

**Issue by jrencz** [jfmdev/ngComboDatePicker#30]
Case:

I have the combo rendered in a way so it has `name` attribute` set to `MyDate` and it's inside a form named `MyForm`:

```html
<form name="MyForm">
  <ng-combo-date-picker name="MyDate" ng-model="$ctrl.someValue"></ng-combo-date-picker>

  <div ng-if="MyForm.MyDate.$touched">Combo was $touched</div>
</form>
```

When I modify year I expect "Combo was $touched" to appear. It doesn't.
NgModelController state flags are not being set.

**Comment by jfmdev** [comment]
The `$touched` and `$untouched` flags are now updated on the last release (1.4.1)
