### ISSUE TITLE
Integrate minification info project

### ISSUE THREAD

**Issue by jrencz** [jfmdev/ngComboDatePicker#31]
As [mentioned in a comment on #29](https://github.com/jfmdev/ngComboDatePicker/pull/29#issuecomment-299611471) the minefield version of the component code should be manually added along with the PR. It should be prepared by a manual usage of of an online tool https://jscompress.com/ which uses uglifyJS under the hood.

I suggest there should be an integrated solution using the same uglifyJS, presumably run with npm script, which will minification the code in a manner controlled from within the project.

**Comment by jfmdev** [comment]
The minified file can now be generated with the command: `npm run-script minify`

Thanks for the suggestion
