### ISSUE TITLE
Year drop down value not getting in fire fox browser after adding condition

### ISSUE THREAD

**Issue by ajayreddy56** [jfmdev/ngComboDatePicker#32]
,it is working fine before applying the maximum year condition in both the browsers. when applying the condition the year drop down not getting.
added plunker and try it in firefox

https://embed.plnkr.co/bgWKBb6MfoCm7sPFPzYU/

**Comment by jfmdev** [comment]
Hi **ajayreddy56**,

This is not an issue on the directive itself, but on your HTML code: you forgot to specify the controller to use (i.e. `ng-controller="myCtrl"`). For some reason, Chrome do not have problem with this, although it should.

Find here the example fixed: https://embed.plnkr.co/wgwNpTKS3cJAIkuhrwZi/

Regards

**Comment by ajayreddy56** [comment]
i have already added in app.js file like

 ```
     .when('/register', {
        templateUrl: 'views/register.html',
        controller: 'RegisterCtrl'
      })
```
 even if i again add in register.html it is no use.

**Comment by ajayreddy56** [comment]
thanks for the reply .working fine

if i use   $scope.maxYear = new Date().getFullYear() -skipYears;
 it is working fine.previously it was 
 var maxYear = new Date().getFullYear() -skipYears;

**Comment by ajayreddy56** [comment]
thanks for the reply .working fine

if i use $scope.maxYear = new Date().getFullYear() -skipYears;
it is working fine.previously it was
var maxYear = new Date().getFullYear() -skipYears;
