### ISSUE TITLE
Not able to set only year, leaving day and month as default

### ISSUE THREAD

**Issue by gvikash16** [jfmdev/ngComboDatePicker#36]
Hi,

There is a requirement that in the year dropdown, current year should be selected by default. "Day" and "Month" should be selected in the "Day" and "Month" drop-down.
As of now, I didn't find any solution for doing this. Because we need to provide the Date object in the ng-model.

**Comment by jfmdev** [comment]
Hi,

The library do not supports partially selecting the combo boxes (you either leave them all in blank, or do you set the value of all of them by initializing the model), however you could clear the values of some combo boxes by using jQuery: https://embed.plnkr.co/UP1Cz3Sm9BDNRX7zqOKt/
