### ISSUE TITLE
Required param has no effect on rendered selects

### ISSUE THREAD

**Issue by jrencz** [jfmdev/ngComboDatePicker#38]
It's even visible on the demo: http://jfmdev.github.io/ngComboDatePicker/

ngRequired is not propagated to the rendered selects

**Comment by jfmdev** [comment]
Hi @jrencz,

I'm not sure which is the issue here. Are you saying that the value in the `ng-required` attribute from `<ng-combo-date-picker>` should be assigned also to the three inner `<select>`?

If that's the case, which is the need of doing this? 

Regards

**Comment by jfmdev** [comment]
Closed due to inactivity
