### ISSUE TITLE
Add a reference to ngx-combo-datepicker

### ISSUE THREAD

**Issue by katafractari** [jfmdev/ngComboDatePicker#39]
Hi!

I'am the author of ngx-combo-datepicker, an Angular 4+ port of this library. Since there's probably some people that land on ngComboDatepicker when searching for a combo datepicker library for Angular 2, my suggestion is that you put a link to my library in the README, like you did for your library reactComboDatePicker.

Thanks!

**Comment by jfmdev** [comment]
Hi **katafractari**, good work! I was planing to eventually implement an Angular 2+ port, but seems you got ahead of me.

I added a link to your project, thanks for your contribution.

**Comment by katafractari** [comment]
@jfmdev Well I have a good incentive for porting it, since we are doing a rewrite of our AngularJS app in Angular 4.
Thanks and cheers!
