### ISSUE TITLE
How do I set blank value as initial date?

### ISSUE THREAD

**Issue by Suresh-Lakum** [jfmdev/ngComboDatePicker#41]
I have tried assigning blank string but didn't work. I have tried assigning null but didn't work.

**Comment by jfmdev** [comment]
Can you share your code?

Normally assigning `null` should work (as show in the [Basic Usage demo](http://jfmdev.github.io/ngComboDatePicker/))

**Comment by Suresh-Lakum** [comment]
When I assign null or empty string it doesn't set placeholders. After that when I try to submit value it says invalid date.

**Comment by jfmdev** [comment]
Can you share your code (at least the part related to this library)?

**Comment by jfmdev** [comment]
Closed due to inactivity
