### ISSUE TITLE
Getting Error while build with Production

### ISSUE THREAD

**Issue by Ganit397** [jfmdev/ngComboDatePicker#43]
We are getting below error while build project with production.

ERROR in node_modules/ngx-combo-datepicker/ngx-combo-datepicker.d.ts.ɵc.html(6,15): : Property 'selects' is private and only accessible within class 
'ComboDatepickerComponent'.
node_modules/ngx-combo-datepicker/ngx-combo-datepicker.d.ts.ɵc.html(4,15): : Property 'selects' is private and only accessible within class 'ComboDatepickerComponent'.
node_modules/ngx-combo-datepicker/ngx-combo-datepicker.d.ts.ɵc.html(7,27): : Property 'selects' is private and only accessible within class 'ComboDatepickerComponent'.
node_modules/ngx-combo-datepicker/ngx-combo-datepicker.d.ts.ɵc.html(8,17): : Property 'selects' is private and only accessible within class 'ComboDatepickerComponent'.
node_modules/ngx-combo-datepicker/ngx-combo-datepicker.d.ts.ɵc.html(4,15): : Property 'selects' is private and only accessible within class 'ComboDatepickerComponent'.
node_modules/ngx-combo-datepicker/ngx-combo-datepicker.d.ts.ɵc.html(5,15): : Expected 0 arguments, but got 1.
node_modules/ngx-combo-datepicker/ngx-combo-datepicker.d.ts.ɵc.html(3,15): : Property 'selects' is private and only accessible within class 'ComboDatepickerComponent'.

**Comment by jfmdev** [comment]
Hi, you should report this bug on https://github.com/katafractari/ngx-combo-datepicker

> **ngComboDatePicker** is the library for Angular 1.x, and you are using **ngx-combo-datepicker** which is Angular 4+.
