### ISSUE TITLE
Add default label for drop down so it isn't blank

### ISSUE THREAD

**Issue by michaelryancaputo** [jfmdev/ngComboDatePicker#6]
Would be great to have a setting that would allow you to set a default label for each field, so they aren't blank.

**Comment by jfmdev** [comment]
Thanks for the suggestion! It's a good idea.
I will implement it in the next release (probably in one or two weeks).

**Comment by jfmdev** [comment]
I have made a new release that implements the `ng-placeholder` attibute, which allow to define the default label for each combo box.

You can see it in action in the [Demo page](http://jfmdev.github.io/ngComboDatePicker/).
