### ISSUE TITLE
Cannot access values on iPhone 6

### ISSUE THREAD

**Issue by Tonimo** [jfmdev/ngComboDatePicker#7]
im using last version (1.2.1) and angular 1.4.10.

after i clicked into the day field i can’t go into the month and year field.
e.g.: i chose day „20"
after having chosed the „20“, the first dropdown shows „20"
then i try to click into the month
what actually happens: the day (!) dropdown opens again and it shows 1 -
the 20 i’ve chosen before disappears and i again have to select the day. can’t reach the other fields.

works fine in Android. please have a look.

**Comment by jfmdev** [comment]
Hi _Tonimo_,

Does this error also occurs when opening the [Demo site](http://jfmdev.github.io/ngComboDatePicker/) or only in your code?

**Comment by jfmdev** [comment]
Close due to inactivity
